services:
  - type: web
    name: priority-planner
    env: python
    buildCommand: ""
    startCommand: gunicorn todo_list.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key-here
      - key: DATABASE_URL
        fromDatabase:
          name: priorityplanner-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11
